// Categories data for the hierarchical story structure
const categories = [
  {
    id: "cat_001",
    slug: "horror",
    name: "Horror Futures",
    parent_slug: "stories",
    description: "Stories where advanced technology creates new forms of terror and psychological horror.",
    icon: "👻",
    banner_image_url: "/banners/horror-futures.jpg",
    display_order: 1,
    story_count: 120,
    featured_story_ids: [21, 22, 23],
    is_active: true,
    color: "from-purple-900 to-gray-900",
    accent_color: "purple"
  },
  {
    id: "cat_002",
    slug: "cyberpunk",
    name: "Cyberpunk Sagas",
    parent_slug: "stories",
    description: "Tales of high-tech, low-life futures where megacorporations rule and hackers fight for freedom.",
    icon: "💻",
    banner_image_url: "/banners/cyberpunk-sagas.jpg",
    display_order: 2,
    story_count: 105,
    featured_story_ids: [24, 25, 26],
    is_active: true,
    color: "from-cyan-900 to-gray-900",
    accent_color: "cyan"
  },
  {
    id: "cat_003",
    slug: "cosmic",
    name: "Cosmic Explorations",
    parent_slug: "stories",
    description: "Journeys to the farthest reaches of space and consciousness, where humanity encounters the infinite.",
    icon: "🚀",
    banner_image_url: "/banners/cosmic-explorations.jpg",
    display_order: 3,
    story_count: 91,
    featured_story_ids: [27, 28, 29],
    is_active: true,
    color: "from-blue-900 to-gray-900",
    accent_color: "blue"
  },
  {
    id: "cat_004",
    slug: "utopian",
    name: "Utopian Visions",
    parent_slug: "stories",
    description: "Optimistic futures where humanity has solved its greatest challenges and created paradise.",
    icon: "🌟",
    banner_image_url: "/banners/utopian-visions.jpg",
    display_order: 4,
    story_count: 76,
    featured_story_ids: [30, 31, 32],
    is_active: true,
    color: "from-green-900 to-gray-900",
    accent_color: "green"
  },
  {
    id: "cat_005",
    slug: "biopunk",
    name: "Biopunk Chronicles",
    parent_slug: "stories",
    description: "Stories where genetic engineering and biological manipulation shape the future of humanity.",
    icon: "🧬",
    banner_image_url: "/banners/biopunk-chronicles.jpg",
    display_order: 5,
    story_count: 92,
    featured_story_ids: [33, 34, 35],
    is_active: true,
    color: "from-emerald-900 to-gray-900",
    accent_color: "emerald"
  },
  {
    id: "cat_006",
    slug: "ai-consciousness",
    name: "AI Consciousness",
    parent_slug: "stories",
    description: "Explorations of artificial intelligence, machine consciousness, and the boundaries between human and digital minds.",
    icon: "🤖",
    banner_image_url: "/banners/ai-consciousness.jpg",
    display_order: 6,
    story_count: 97,
    featured_story_ids: [36, 37, 38],
    is_active: true,
    color: "from-amber-900 to-gray-900",
    accent_color: "amber"
  },
  {
    id: "cat_007",
    slug: "time-paradox",
    name: "Time Paradox",
    parent_slug: "stories",
    description: "Mind-bending adventures through temporal dimensions and paradoxical realities.",
    icon: "⏰",
    banner_image_url: "/banners/time-paradox.jpg",
    display_order: 7,
    story_count: 87,
    featured_story_ids: [39, 40, 41],
    is_active: true,
    color: "from-violet-900 to-gray-900",
    accent_color: "violet"
  },
  {
    id: "cat_008",
    slug: "galactic",
    name: "Galactic Empires",
    parent_slug: "stories",
    description: "Epic tales of interstellar civilizations, galactic politics, and cosmic-scale conflicts.",
    icon: "🌌",
    banner_image_url: "/banners/galactic-empires.jpg",
    display_order: 8,
    story_count: 95,
    featured_story_ids: [42, 43, 44],
    is_active: true,
    color: "from-indigo-900 to-gray-900",
    accent_color: "indigo"
  },
  {
    id: "cat_009",
    slug: "post-human",
    name: "Post-Human",
    parent_slug: "stories",
    description: "Stories exploring humanity's evolution beyond biological limitations through technology and consciousness.",
    icon: "🧠",
    banner_image_url: "/banners/post-human.jpg",
    display_order: 9,
    story_count: 98,
    featured_story_ids: [45, 46, 47],
    is_active: true,
    color: "from-pink-900 to-gray-900",
    accent_color: "pink"
  },
  {
    id: "cat_010",
    slug: "alt-history",
    name: "Alternative Histories",
    parent_slug: "stories",
    description: "What if pivotal moments in history had unfolded differently? Exploring divergent timelines.",
    icon: "📜",
    banner_image_url: "/banners/alt-history.jpg",
    display_order: 10,
    story_count: 74,
    featured_story_ids: [48, 49, 50],
    is_active: true,
    color: "from-rose-900 to-gray-900",
    accent_color: "rose"
  },
  {
    id: "cat_011",
    slug: "quantum",
    name: "Quantum Realities",
    parent_slug: "stories",
    description: "Stories where quantum mechanics and parallel universes create infinite possibilities.",
    icon: "⚛️",
    banner_image_url: "/banners/quantum-realities.jpg",
    display_order: 11,
    story_count: 91,
    featured_story_ids: [51, 52, 53],
    is_active: true,
    color: "from-teal-900 to-gray-900",
    accent_color: "teal"
  },
  {
    id: "cat_012",
    slug: "solarpunk",
    name: "Solarpunk Serenity",
    parent_slug: "stories",
    description: "Optimistic visions of sustainable futures where technology harmonizes with nature.",
    icon: "☀️",
    banner_image_url: "/banners/solarpunk-serenity.jpg",
    display_order: 12,
    story_count: 70,
    featured_story_ids: [54, 55, 56],
    is_active: true,
    color: "from-lime-900 to-gray-900",
    accent_color: "lime"
  }
];

export default categories;